# Project information
site_name: 'Thales Open Source'
site_description: 'Thales Open Source'
site_author: 'Thales'
site_url: 'https://thalesgroup.github.io/'


# Copyright
copyright: |
  Copyright &copy; 2023 THALES<br>

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
     - navigation.tabs

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/ThalesGroup'